// ---------------------------------------------------------------------------
// Affiliate settings
// Replace AMAZON_TAG with your Amazon Associates tracking ID (ends in -21 for amazon.co.uk).
// For any product, set `asin` to link straight to a product page instead of a search.
// ---------------------------------------------------------------------------
const AMAZON_TAG = "readyhomeuk-21";

const CATEGORIES = [
  { id: "all", label: "Everything" },
  { id: "power", label: "Power cuts" },
  { id: "water", label: "Water & food" },
  { id: "health", label: "First aid & hygiene" },
  { id: "family", label: "Babies & pets" },
  { id: "safety", label: "Home safety" },
  { id: "car", label: "Car & grab bag" },
];

// Helpers used in quantity text. `h` = { adults, children, babies, pets }.
const people = (h) => h.adults + h.children + h.babies;
const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`;

const PRODUCTS = [
  {
    id: "torch",
    name: "Wind-up or battery torch",
    category: "power",
    official: true,
    icon: "torch",
    tone: "amber",
    summary: "Light that works when the mains is off. Far safer than candles.",
    why: "The government's Prepare campaign lists a battery or wind-up torch first, because candles are a leading cause of house fires during power cuts. A wind-up model never runs out of batteries.",
    lookFor: [
      "A hand-crank or USB-rechargeable LED torch, ideally with both",
      "At least 100 lumens for moving around the house",
      "A head torch as well, so your hands are free",
    ],
    qty: (h) => `${plural(Math.max(1, h.adults), "torch", "torches")}, one per adult`,
    query: "wind up rechargeable LED torch",
    asin: null,
  },
  {
    id: "powerbank",
    name: "Portable power bank",
    category: "power",
    official: true,
    icon: "powerbank",
    tone: "teal",
    summary: "Keeps phones charged so you can get alerts and call for help.",
    why: "Your phone receives the government's Emergency Alerts and is how you'll contact family. A charged power bank gives several full phone charges during a long outage.",
    lookFor: [
      "20,000 mAh or more for several phone charges",
      "The right cables for every phone in the house",
      "Keep it topped up: check and recharge every three months",
    ],
    qty: (h) => `${plural(Math.max(1, Math.ceil(h.adults / 2)), "power bank", "power banks")} of 20,000 mAh`,
    query: "power bank 20000mAh",
    asin: null,
  },
  {
    id: "radio",
    name: "Wind-up or battery radio",
    category: "power",
    official: true,
    icon: "radio",
    tone: "violet",
    summary: "Hear official updates even when the internet and mobile networks are down.",
    why: "Local and national radio broadcast emergency updates during power cuts. The government recommends a battery or wind-up radio so you are not relying on mobile data.",
    lookFor: [
      "Hand-crank and solar charging, with batteries as back-up",
      "FM/AM is enough for BBC local radio and emergency updates",
      "A built-in torch and USB phone-charging port are useful extras",
    ],
    qty: () => "1 per household",
    query: "wind up solar emergency radio FM DAB",
    asin: "B0FBR82LMV", // ROCAM FM/AM wind-up solar radio
  },
  {
    id: "batteries",
    name: "Spare batteries",
    category: "power",
    official: true,
    icon: "batteries",
    tone: "amber",
    summary: "For torches, radios, smoke alarms and any medical equipment.",
    why: "The guidance asks you to keep spare batteries for torches, radios and medical devices. Alkaline batteries keep for up to ten years in a drawer.",
    lookFor: [
      "Check which sizes your torch, radio and alarms take (usually AA and AAA)",
      "Long-life alkaline for storage, not rechargeables that slowly drain",
      "Write the expiry year on the pack",
    ],
    qty: () => "A multipack of AA and AAA",
    query: "AA AAA alkaline batteries multipack long life",
    asin: null,
  },
  {
    id: "firstaid",
    name: "First aid kit",
    category: "health",
    official: true,
    icon: "firstaid",
    tone: "rose",
    summary: "Plasters, bandages, dressings, antiseptic and the basics to treat minor injuries.",
    why: "When ambulances and GP surgeries are stretched you may need to deal with minor injuries yourself. The government suggests plasters, bandages, a thermometer, antiseptic, eyewash, sterile dressings, gloves, medical tape and tweezers.",
    lookFor: [
      "A kit that meets British Standard BS 8599-1 for home or workplace use",
      "A digital thermometer if the kit doesn't include one",
      "A first aid guide booklet, in case the internet is down",
    ],
    qty: (h) => (people(h) > 4 ? "1 large kit (family size)" : "1 home kit"),
    query: "first aid kit home BS 8599",
    asin: null,
  },
  {
    id: "medication",
    name: "Pill organiser & medicine bag",
    category: "health",
    official: true,
    icon: "pills",
    tone: "violet",
    summary: "Keep several days of essential medication sorted and ready to go.",
    why: "The government advises having enough of your regular medication to last several days, in case pharmacies are closed or you can't travel. An organiser makes it easy to grab and go.",
    lookFor: [
      "A weekly pill organiser with clearly marked days",
      "A small insulated bag if any medicine needs to stay cool",
      "Keep a paper copy of every prescription in the bag",
    ],
    qty: () => "1 per person on regular medication",
    query: "weekly pill organiser travel medicine bag",
    asin: null,
  },
  {
    id: "sanitiser",
    name: "Hand sanitiser & wet wipes",
    category: "health",
    official: true,
    icon: "sanitiser",
    tone: "teal",
    summary: "Stay clean and healthy when the taps don't work.",
    why: "If your water supply is cut off, hand sanitiser and wet wipes are the government's recommended way to keep hands and surfaces clean and stop illness spreading.",
    lookFor: [
      "Sanitiser with at least 60% alcohol",
      "Large packs of unscented wet wipes",
      "Bin bags for waste if collections stop",
    ],
    qty: (h) => `${plural(Math.max(1, Math.ceil(people(h) / 2)), "bottle", "bottles")} of sanitiser and ${plural(Math.max(2, people(h)), "pack", "packs")} of wipes`,
    query: "hand sanitiser 60% alcohol and wet wipes bulk",
    asin: null,
  },
  {
    id: "water",
    name: "Bottled water",
    category: "water",
    official: true,
    icon: "water",
    tone: "sky",
    summary: "The single most important thing in your kit.",
    why: "The government recommends 2.5 to 3 litres per person per day just to drink, or 10 litres per person per day to cover cooking and washing. Plan for at least three days.",
    lookFor: [
      "Sealed multipacks of still water, the cheapest and safest option",
      "Store in a cool, dark place, off the floor",
      "Use and replace it before the best-before date",
    ],
    qty: (h) => {
      const p = people(h);
      return `${p * 9} litres minimum, ${p * 30} litres ideal (3 days)`;
    },
    query: "still bottled water multipack 2 litre",
    asin: null,
  },
  {
    id: "jerrycan",
    name: "Water storage container",
    category: "water",
    official: false,
    icon: "jerrycan",
    tone: "teal",
    summary: "Fill up from the tap the moment a water outage is announced.",
    why: "Bottled water covers drinking. A food-grade container lets you store extra tap water for washing and flushing when you get a warning that supplies may be cut.",
    lookFor: [
      "Food-grade, BPA-free plastic with a tap",
      "Collapsible designs save space when empty",
      "10 to 20 litres is as much as most people can lift",
    ],
    qty: (h) => `${plural(Math.max(1, Math.ceil(people(h) / 2)), "container", "containers")} of 10–20 litres`,
    query: "collapsible water container with tap food grade 20 litre",
    asin: null,
  },
  {
    id: "food",
    name: "Long-life food",
    category: "water",
    official: true,
    icon: "tins",
    tone: "sage",
    summary: "Food you can eat without cooking: tins, pouches and snacks.",
    why: "The guidance recommends non-perishable food that doesn't need cooking, like tinned meat and vegetables, because you may have no power to cook with.",
    lookFor: [
      "Ring-pull tins, so you don't even need an opener",
      "Ready-to-eat pouches, oat bars, nuts and dried fruit",
      "Food your household actually likes, so you can rotate it into normal meals",
    ],
    qty: (h) => `${people(h) * 9} meals for 3 days, plus snacks`,
    query: "ring pull tinned food ready to eat",
    asin: null,
  },
  {
    id: "rations",
    name: "Emergency food rations",
    category: "water",
    official: false,
    icon: "rations",
    tone: "sage",
    summary: "Compact, long shelf life bars that you can forget about for years.",
    why: "Emergency ration bars last five years or more and need no water or cooking. They are a good back-up to your everyday tins and are ideal for a grab bag.",
    lookFor: [
      "A shelf life of at least five years",
      "Around 2,400 calories per person per day",
      "Individually wrapped portions",
    ],
    qty: (h) => `${plural(people(h) * 3, "day's ration", "days' rations")}`,
    query: "emergency food ration bars 5 year shelf life",
    asin: null,
  },
  {
    id: "opener",
    name: "Manual tin opener",
    category: "water",
    official: true,
    icon: "opener",
    tone: "amber",
    summary: "An electric opener won't help you in a power cut.",
    why: "The government specifically mentions keeping a tin opener alongside tinned food. A simple manual one is cheap and lasts for years.",
    lookFor: [
      "A sturdy stainless steel, hand-turned opener",
      "Comfortable grip handles",
      "Keep it with the food, not in the kitchen drawer",
    ],
    qty: () => "1 per household",
    query: "manual tin opener stainless steel",
    asin: null,
  },
  {
    id: "baby",
    name: "Ready-to-feed baby formula",
    category: "family",
    official: true,
    icon: "baby",
    tone: "rose",
    summary: "No boiling water needed, so it works when the power is off.",
    why: "The government says ready-made or 'ready-to-feed' formula is best in an emergency, because you may not be able to boil water to make up powdered formula safely.",
    lookFor: [
      "The same brand and stage your baby already uses",
      "Single-use bottles and teats, or a sterile starter pack",
      "Check use-by dates and rotate stock monthly",
    ],
    qty: (h) => (h.babies ? `About ${h.babies * 18} bottles (3 days)` : "Only if you have a baby at home"),
    query: "ready to feed baby formula starter pack",
    asin: null,
    showWhen: (h) => h.babies > 0,
  },
  {
    id: "pets",
    name: "Long-life pet food",
    category: "family",
    official: true,
    icon: "paw",
    tone: "sage",
    summary: "Don't forget the four-legged members of the household.",
    why: "The government reminds households to include food for pets. Keep a few extra days of their usual food, plus water for them too.",
    lookFor: [
      "Their usual food, so you don't upset their stomach",
      "Sealed pouches or tins with a long date",
      "A collapsible water bowl",
    ],
    qty: (h) => (h.pets ? `3 days of food for ${plural(h.pets, "pet", "pets")}` : "Only if you have pets"),
    query: "pet food pouches multipack long life",
    asin: null,
    showWhen: (h) => h.pets > 0,
  },
  {
    id: "blanket",
    name: "Foil emergency blankets",
    category: "car",
    official: false,
    icon: "blanket",
    tone: "sky",
    summary: "Light, cheap and they keep in body heat during a winter power cut.",
    why: "Without power most central heating stops. Foil blankets weigh almost nothing and help keep people warm, especially older people and young children who feel the cold faster.",
    lookFor: [
      "A pack of several blankets, at least 130 x 210 cm",
      "Keep warm layers and normal blankets with your kit too",
      "Put one or two in the car for winter",
    ],
    qty: (h) => `${plural(Math.max(2, people(h)), "blanket", "blankets")}`,
    query: "foil emergency thermal blanket pack",
    asin: null,
  },
  {
    id: "grabbag",
    name: "Grab bag",
    category: "car",
    official: false,
    icon: "bag",
    tone: "amber",
    summary: "A ready-packed bag in case you need to leave home quickly.",
    why: "If you're asked to evacuate because of flooding or fire, you may have minutes to leave. A packed bag by the door holds your essentials, documents and medication.",
    lookFor: [
      "A waterproof rucksack of 30 to 40 litres",
      "Easy to carry for the smallest adult in the house",
      "Pack a torch, water, snacks, medication, chargers and copies of documents",
    ],
    qty: () => "1 per household",
    query: "waterproof rucksack 35 litre",
    asin: null,
  },
  {
    id: "wallet",
    name: "Waterproof document wallet",
    category: "car",
    official: false,
    icon: "wallet",
    tone: "violet",
    summary: "Keep your emergency plan, IDs and important numbers safe and dry.",
    why: "The government suggests writing a household emergency plan and keeping important phone numbers on paper. A waterproof wallet protects these, plus copies of passports, insurance and prescriptions.",
    lookFor: [
      "A zip-sealed, waterproof A4 wallet",
      "Room for your printed household emergency plan",
      "A little cash in small notes, in case card machines are down",
    ],
    qty: () => "1 per household",
    query: "waterproof document wallet A4 zip",
    asin: null,
  },
  {
    id: "car",
    name: "Winter car kit",
    category: "car",
    official: true,
    icon: "car",
    tone: "sage",
    summary: "Ice scraper, shovel, jump leads and warm things for the boot.",
    why: "For winter travel the government suggests a torch, phone charger, warm clothes, blankets, high-visibility clothing, jump leads, food and drink, a shovel and a first aid kit in the car.",
    lookFor: [
      "A folding snow shovel and ice scraper",
      "Jump leads or a portable jump starter",
      "A hi-vis vest for every seat",
    ],
    qty: () => "1 per car",
    query: "winter car emergency kit jump leads shovel",
    asin: null,
  },
  {
    id: "smoke",
    name: "Smoke alarms",
    category: "safety",
    official: true,
    icon: "smoke",
    tone: "rose",
    summary: "One on every floor. Test them every month.",
    why: "The Prepare campaign tells households to test smoke alarms at least monthly. Fires are more likely in power cuts, when people use candles and heaters.",
    lookFor: [
      "10-year sealed battery models, so there is no battery to forget",
      "Interlinked alarms, so all sound when one does",
      "One on every floor of your home",
    ],
    qty: () => "At least 1 per floor",
    query: "smoke alarm 10 year sealed battery",
    asin: null,
  },
  {
    id: "co",
    name: "Carbon monoxide alarm",
    category: "safety",
    official: false,
    icon: "co",
    tone: "amber",
    summary: "Warns you of a gas you can't see or smell.",
    why: "Carbon monoxide risk rises when people use gas heaters, generators or barbecues indoors during a power cut. An alarm is required by law in many rented homes in the UK.",
    lookFor: [
      "Certified to BS EN 50291",
      "Sealed battery that lasts the life of the alarm",
      "Fit one in every room with a boiler, fire or stove",
    ],
    qty: () => "1 per room with a fuel-burning appliance",
    query: "carbon monoxide alarm BS EN 50291",
    asin: null,
  },
];

function amazonUrl(product) {
  const tag = encodeURIComponent(AMAZON_TAG);
  if (product.asin) return `https://www.amazon.co.uk/dp/${product.asin}?tag=${tag}`;
  return `https://www.amazon.co.uk/s?k=${encodeURIComponent(product.query)}&tag=${tag}`;
}

const SITUATIONS = [
  { photo: "powercut", title: "Power cuts", text: "Light, heat and a charged phone", filter: "power" },
  { photo: "flood", title: "Flooding", text: "A grab bag ready to go", filter: "car" },
  { photo: "storm", title: "Severe storms", text: "Stay safe and informed", filter: "power" },
  { photo: "outage", title: "Water outages", text: "Drinking water for 3 days", filter: "water" },
  { photo: "heat", title: "Heatwaves & cold snaps", text: "Protect the most vulnerable", filter: "health" },
  { photo: "cyber", title: "Cyber attacks", text: "When cards and phones go down", filter: "all" },
];
